// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyUpdate downloads the platform-specific release, verifies its SHA-256
 * digest, stages it, and restarts Dockiva through Wails' detached updater
 * helper. The running application is only replaced after it has exited.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(833371355);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3671876993);
}

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3018893939);
}

export function GetVersionInfo(): $CancellablePromise<$models.VersionInfo> {
    return $Call.ByID(648089650);
}

export function OpenUpdatePage(releaseURL: string): $CancellablePromise<void> {
    return $Call.ByID(2539713760, releaseURL);
}

export function Snapshot(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3423517222);
}

export function UpdateSettings(next: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3899138734, next);
}
