// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3018893939);
}

export function Snapshot(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3423517222);
}

export function UpdateSettings(next: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3899138734, next);
}
