// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AutoRecoverEngine(backend: string, platformOption: string, autoReconnect: boolean, startEngine: boolean): $CancellablePromise<void> {
    return $Call.ByID(3004408452, backend, platformOption, autoReconnect, startEngine);
}

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2250375291, sessionID);
}

export function ComposeProjectAction(project: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(2338442158, project, action);
}

/**
 * ConfigureDockerEndpoint binds the Docker client to the saved engine identity
 * without requiring that engine to be online yet.
 */
export function ConfigureDockerEndpoint(endpoint: string): $CancellablePromise<void> {
    return $Call.ByID(530670802, endpoint);
}

export function ConfiguredDockerEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(1471947120);
}

export function CreateNetwork(name: string, driver: string): $CancellablePromise<$models.DockerCLIResult> {
    return $Call.ByID(1838847225, name, driver);
}

export function CreateVolume(name: string, driver: string): $CancellablePromise<$models.DockerCLIResult> {
    return $Call.ByID(3452102387, name, driver);
}

export function DeleteManagedEngine(backend: string, platformOption: string): $CancellablePromise<$models.EngineActionResult> {
    return $Call.ByID(110256389, backend, platformOption);
}

export function DiscoverDockerEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(1316634347);
}

export function DockerEndpointIdentity(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2541309170);
}

export function GetComposeProjectDetails(project: string): $CancellablePromise<$models.ComposeProjectDetails> {
    return $Call.ByID(441200772, project);
}

export function GetContainerDetails(containerID: string): $CancellablePromise<$models.ContainerDetails> {
    return $Call.ByID(913307772, containerID);
}

export function GetContainerStats(containerIDs: string[] | null): $CancellablePromise<$models.ContainerResourceStats[] | null> {
    return $Call.ByID(336926749, containerIDs);
}

export function GetDiskUsage(): $CancellablePromise<$models.DockerDiskUsageItem[] | null> {
    return $Call.ByID(3957457885);
}

export function GetEngineStatus(backend: string, platformOption: string): $CancellablePromise<$models.EngineStatus> {
    return $Call.ByID(2567748191, backend, platformOption);
}

export function GetPlatformInfo(): $CancellablePromise<$models.PlatformInfo> {
    return $Call.ByID(1468930408);
}

export function GetRuntimeOverview(): $CancellablePromise<$models.RuntimeOverview> {
    return $Call.ByID(1178048546);
}

export function ImportComposePath(inputPath: string): $CancellablePromise<$models.ComposeImportResult> {
    return $Call.ByID(383608731, inputPath);
}

export function ListContainers(): $CancellablePromise<$models.ContainerInfo[] | null> {
    return $Call.ByID(3901828385);
}

export function ListImages(): $CancellablePromise<$models.ImageInfo[] | null> {
    return $Call.ByID(1387658235);
}

export function ListNetworks(): $CancellablePromise<$models.NetworkInfo[] | null> {
    return $Call.ByID(2271379954);
}

export function ListVolumes(): $CancellablePromise<$models.VolumeInfo[] | null> {
    return $Call.ByID(3749554852);
}

/**
 * ListWSLDistros keeps the existing API stable. It returns an empty list on
 * platforms whose engine backend has no distro selector.
 */
export function ListWSLDistros(): $CancellablePromise<string[] | null> {
    return $Call.ByID(938667263);
}

/**
 * ProvisionWSLEngine is intentionally kept as a stable Wails binding so the
 * current frontend does not need OS-specific generated bindings. On non-Windows
 * builds the platform backend returns a clear unsupported error.
 */
export function ProvisionWSLEngine(platformOption: string): $CancellablePromise<$models.EngineActionResult> {
    return $Call.ByID(748723644, platformOption);
}

export function PruneDocker(scope: string): $CancellablePromise<$models.DockerCLIResult> {
    return $Call.ByID(3370203467, scope);
}

export function PullImage(reference: string): $CancellablePromise<$models.DockerCLIResult> {
    return $Call.ByID(500241135, reference);
}

export function ReconnectConfiguredDocker(): $CancellablePromise<void> {
    return $Call.ByID(2102687070);
}

export function ReconnectExternalDocker(): $CancellablePromise<void> {
    return $Call.ByID(3506397529);
}

export function RecoverDockerConnection(): $CancellablePromise<$models.EngineActionResult> {
    return $Call.ByID(254285255);
}

export function RemoveContainer(containerID: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(3474080716, containerID, force);
}

export function RemoveImage(imageID: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1019712286, imageID, force);
}

export function RemoveNetwork(networkID: string): $CancellablePromise<void> {
    return $Call.ByID(2905169785, networkID);
}

export function RemoveVolume(name: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(486638195, name, force);
}

export function ResizeTerminal(sessionID: string, width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(128688305, sessionID, width, height);
}

export function RestartContainer(containerID: string): $CancellablePromise<void> {
    return $Call.ByID(2239070055, containerID);
}

export function RunComposeCommand(project: string, action: string): $CancellablePromise<$models.DockerCLIResult> {
    return $Call.ByID(4079336887, project, action);
}

export function RuntimeCreateContainer(name: string, image: string, command: string[] | null, autoStart: boolean, portMappings: $models.RuntimePortMapping[] | null): $CancellablePromise<$models.ContainerInfo> {
    return $Call.ByID(1641684482, name, image, command, autoStart, portMappings);
}

export function RuntimePullImage(reference: string): $CancellablePromise<$models.RuntimeOperationResult> {
    return $Call.ByID(2976361949, reference);
}

export function SelectComposeFile(): $CancellablePromise<string> {
    return $Call.ByID(3175236089);
}

export function SelectComposeFolder(): $CancellablePromise<string> {
    return $Call.ByID(1053944883);
}

export function SelectContainerRuntime(provider: string): $CancellablePromise<void> {
    return $Call.ByID(2117074216, provider);
}

/**
 * SelectEngineBackend keeps the top-level engine choice and active runtime in
 * sync. A stopped native engine deliberately installs an offline runtime so a
 * previously connected external Docker daemon cannot leak into the UI.
 */
export function SelectEngineBackend(backend: string, platformOption: string, externalEndpoint: string): $CancellablePromise<string> {
    return $Call.ByID(2734271629, backend, platformOption, externalEndpoint);
}

export function SendTerminalInput(sessionID: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(541440005, sessionID, input);
}

export function SetConfiguredDockerEndpoint(endpoint: string): $CancellablePromise<void> {
    return $Call.ByID(2251554858, endpoint);
}

export function StartContainer(containerID: string): $CancellablePromise<void> {
    return $Call.ByID(1046942246, containerID);
}

/**
 * StartLogStream follows Docker logs until StopLogStream is called or the
 * container log stream ends. Output is emitted as "devstack:log-output".
 */
export function StartLogStream(containerID: string, tail: number): $CancellablePromise<string> {
    return $Call.ByID(1202017299, containerID, tail);
}

export function StartManagedEngine(backend: string, platformOption: string): $CancellablePromise<$models.EngineActionResult> {
    return $Call.ByID(500989482, backend, platformOption);
}

/**
 * StartTerminal creates a persistent /bin/sh exec session with a TTY.
 * The frontend receives output through the "devstack:terminal-output" event.
 */
export function StartTerminal(containerID: string): $CancellablePromise<string> {
    return $Call.ByID(2636107271, containerID);
}

export function Status(): $CancellablePromise<$models.DockerStatus> {
    return $Call.ByID(461657515);
}

export function StopContainer(containerID: string): $CancellablePromise<void> {
    return $Call.ByID(1570398764, containerID);
}

export function StopLogStream(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(1269178085, streamID);
}

export function StopManagedEngine(backend: string, platformOption: string): $CancellablePromise<$models.EngineActionResult> {
    return $Call.ByID(871673504, backend, platformOption);
}

/**
 * SwitchDockerEndpoint verifies a new endpoint before atomically making it the
 * active client. The previous client remains alive until application shutdown
 * so an in-flight request is not invalidated by an engine switch.
 */
export function SwitchDockerEndpoint(endpoint: string): $CancellablePromise<void> {
    return $Call.ByID(2837965908, endpoint);
}
