// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppSettings {
    "settingsVersion": number;
    "engineBackend": string;
    "runtimeProvider": string;
    "dockerEndpoint": string;
    "wslDistro": string;
    "closeToTray": boolean;
    "startAtLogin": boolean;
    "startHidden": boolean;
    "autoReconnectEngine": boolean;
    "startEngineOnLaunch": boolean;
}

export interface ComposeImportResult {
    "project": string;
    "workingDir": string;
    "configFiles": string[] | null;
    "output": string;
}

export interface ComposeProjectDetails {
    "project": string;
    "workingDir": string;
    "configFiles": string[] | null;
    "envFile"?: string;
}

export interface ContainerDetails {
    "id": string;
    "name": string;
    "image": string;
    "created": string;
    "path": string;
    "args": string[] | null;
    "entrypoint": string[] | null;
    "command": string[] | null;
    "workingDir": string;
    "user": string;
    "environment": string[] | null;
    "mounts": ContainerMountDetail[] | null;
    "networks": ContainerNetworkDetail[] | null;
    "labels": { [_ in string]?: string } | null;
    "restartPolicy": string;
    "state": string;
    "exitCode": number;
    "startedAt": string;
    "finishedAt": string;
}

export interface ContainerInfo {
    "id": string;
    "shortId": string;
    "name": string;
    "image": string;
    "state": string;
    "status": string;
    "composeProject"?: string;
    "composeService"?: string;
    "ipAddress"?: string;
    "ports": PortInfo[] | null;
}

export interface ContainerMountDetail {
    "type": string;
    "name"?: string;
    "source": string;
    "destination": string;
    "rw": boolean;
}

export interface ContainerNetworkDetail {
    "name": string;
    "ipAddress": string;
    "gateway": string;
    "mac": string;
}

export interface ContainerResourceStats {
    "id": string;
    "cpuPercent": number;
    "memoryUsage": number;
    "memoryLimit": number;
    "memoryPercent": number;
    "pids": number;
    "error"?: string;
}

export interface ContainerRuntimeInfo {
    "provider": string;
    "displayName": string;
    "endpoint"?: string;
    "connected": boolean;
    "experimental": boolean;
    "capabilities": RuntimeCapabilities;
    "message"?: string;
}

export interface DockerCLIResult {
    "output": string;
}

export interface DockerDiskUsageItem {
    "type": string;
    "totalCount": number;
    "active": number;
    "size": string;
    "reclaimable": string;
}

export interface DockerStatus {
    "connected": boolean;
    "apiVersion": string;
    "osType": string;
    "error"?: string;
}

export interface EngineActionResult {
    "status": EngineStatus;
    "output"?: string;
}

export interface EngineStatus {
    "backend": string;
    "platform": string;
    "supported": boolean;
    "helperInstalled": boolean;
    "engineInstalled": boolean;
    "running": boolean;
    "endpoint"?: string;
    "message"?: string;
    "wslDistros"?: string[] | null;
}

export interface ImageInfo {
    "id": string;
    "shortId": string;
    "tags": string[] | null;
    "size": number;
    "created": number;
    "containers": number;
}

export interface NetworkInfo {
    "id": string;
    "shortId": string;
    "name": string;
    "driver": string;
    "scope": string;
    "internal": boolean;
    "attachable": boolean;
    "ingress": boolean;
}

export interface PlatformInfo {
    "os": string;
    "arch": string;
    "dockerCli"?: string;
    "dockerContext"?: string;
    "dockerHost"?: string;
    "hostSource"?: string;
}

export interface PortInfo {
    "privatePort": number;
    "publicPort": number;
    "type": string;
    "display": string;
    "url"?: string;
}

export interface RuntimeCandidateInfo {
    "provider": string;
    "displayName": string;
    "available": boolean;
    "detected": boolean;
    "selectable": boolean;
    "experimental": boolean;
    "endpoint"?: string;
    "message"?: string;
}

export interface RuntimeCapabilities {
    "containers": boolean;
    "lifecycle": boolean;
    "stats": boolean;
    "logs": boolean;
    "terminal": boolean;
    "images": boolean;
    "pullImages": boolean;
    "createContainer": boolean;
    "volumes": boolean;
    "networks": boolean;
    "portPublishing": boolean;
    "dns": boolean;
    "compose": boolean;
}

export interface RuntimeOperationResult {
    "message": string;
    "detail"?: string;
}

export interface RuntimeOverview {
    "active": ContainerRuntimeInfo;
    "candidates": RuntimeCandidateInfo[] | null;
}

export interface RuntimePortMapping {
    "hostPort": number;
    "containerPort": number;
    "protocol": string;
    "hostIp": string;
}

export interface VolumeInfo {
    "name": string;
    "driver": string;
    "scope": string;
    "mountpoint": string;
    "createdAt"?: string;
    "labels": { [_ in string]?: string } | null;
}
